// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Brandon Scott

package com.xeonproductions.craftbookultimate.paper.command;

import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import com.mojang.brigadier.context.CommandContext;
import io.papermc.paper.command.brigadier.CommandSourceStack;
import io.papermc.paper.command.brigadier.Commands;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.material.MaterialData;
import org.bukkit.plugin.Plugin;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Writing out how a 1.12 sign's block spellings map onto today's blocks.
 *
 * <p>Signs naming a block as {@code 35:14} are the common case in the worlds this plugin is for,
 * and reading one means knowing what {@code 35:14} became. Bukkit knows, because its
 * {@code fromLegacy} runs the game's own data fixers; nothing outside a Bukkit server does, and the
 * Sponge build in particular has no way to ask. So the answer is written down here, once, by the
 * one platform that can give it, and carried as data everywhere else.
 *
 * <p>It is a command rather than a build step because the data fixers need a running game. What it
 * writes is {@code legacy-blocks.properties} in the plugin's folder, to be dropped into the Sponge
 * jar's resources.
 */
@NullMarked
public final class LegacyTableCommands {

    public static final String LEGACY_TABLE = "craftbook.legacytable";

    /** The damage values a 1.12 block could carry. */
    private static final int MAX_DAMAGE = 15;

    private static final int SUCCESS = 1;

    private static final String FILE = "legacy-blocks.properties";

    private final Plugin plugin;

    public LegacyTableCommands(Plugin plugin) {
        this.plugin = plugin;
    }

    public LiteralArgumentBuilder<CommandSourceStack> legacyTableCommand() {
        return Commands.literal("legacytable")
                .requires(source -> source.getSender().hasPermission(LEGACY_TABLE))
                .executes(this::write);
    }

    private int write(CommandContext<CommandSourceStack> context) {
        Path target = plugin.getDataFolder().toPath().resolve(FILE);
        List<String> lines = table();

        try {
            Files.createDirectories(target.getParent());
            Files.write(target, lines, StandardCharsets.UTF_8);
        } catch (IOException e) {
            context.getSource().getSender().sendMessage(
                    Component.text("Could not write " + FILE + ": " + e.getMessage(),
                            NamedTextColor.RED));
            return SUCCESS;
        }

        context.getSource().getSender().sendMessage(Component.text(
                "Wrote " + (lines.size() - HEADER.size()) + " legacy spellings to " + target,
                NamedTextColor.GREEN));
        return SUCCESS;
    }

    private static final List<String> HEADER = List.of(
            "# How blocks were spelled before the flattening, and what each became.",
            "# Generated by /craftbook legacytable on a Bukkit server; do not edit by hand.",
            "# One line per spelling: kind|spelling:damage|modern key");

    private static List<String> table() {
        List<String> lines = new ArrayList<>(HEADER);

        for (Material legacy : Material.values()) {
            if (!legacy.isLegacy()) {
                continue;
            }
            for (int damage = 0; damage <= MAX_DAMAGE; damage++) {
                append(lines, "block", legacy, damage, false);
                append(lines, "item", legacy, damage, true);
            }
        }

        return lines;
    }

    private static void append(
            List<String> lines, String kind, Material legacy, int damage, boolean asItem) {
        Material modern = fromLegacy(legacy, damage, asItem);
        if (modern == null || modern == Material.AIR || (asItem ? !modern.isItem() : !modern.isBlock())) {
            return;
        }

        String key = modern.getKey().asString();

        // Both spellings a sign may carry: the number the block had, and the name it had. The
        // LEGACY_ prefix Bukkit gives these is Bukkit's own and never appeared on a sign.
        String name = legacy.name().toLowerCase(Locale.ROOT).replaceFirst("^legacy_", "");
        lines.add(kind + '|' + name + ':' + damage + '|' + key);
        lines.add(kind + '|' + legacy.getId() + ':' + damage + '|' + key);
    }

    @SuppressWarnings({"deprecation", "removal"})
    private static @Nullable Material fromLegacy(Material legacy, int damage, boolean asItem) {
        try {
            return Bukkit.getUnsafe().fromLegacy(new MaterialData(legacy, (byte) damage), asItem);
        } catch (RuntimeException e) {
            // A damage value that block never had. Nothing to record, and nothing wrong.
            return null;
        }
    }
}
